# CustomLibs

site_name: pGenUtils Documentation
site_description: 'Documentation for the custom package pLabUtils'
site_author: 'Timothe'
site_url: 'https://josttim.github.io/pLabUtils/'

repo_name: 'pGenUtils'
repo_url: 'https://github.com/JostTim/pLabUtils'
edit_uri: ''

copyright: '&copy; 2021 Timothe'

use_directory_urls: false

docs_dir: 'doc'

theme:
    name: 'material'
    palette :
    
        - scheme: default
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
        - scheme: slate
          primary: deep orange
          accent: teal
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
            
    features:
        - navigation.tabs
        - navigation.instant
        - navigation.top
    highlightjs : true
    hljs_languages :
        - python
        - c++
        - c
        - html
        - css
        - cmd

markdown_extensions:
  #- navigation.instant
  - meta
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - footnotes
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - search
    #- autorefs
    - mkdocstrings :
        handlers:
          python:
            rendering:
              show_category_heading : false
              show_source: false
              show_if_no_docstring : true
              show_signature_annotations : true
              #show_root_heading : false
              heading_level : 2
            selection:
              #docstring_style: google  # this is the default
              #docstring_options:
                #replace_admonitions: yes 
              filters:
                - "!^_"  # exlude all members starting with _
                - "^__init__$"  # but always include __init__ modules and methods
                - '!^"""Boilerplate:$'
                - "!^@property"
    
nav:
    - Usage: index.md
    - dicts: 
        - 'keep_matched_keys': 'dicts\keep_matched_keys.md'
        - 'drop_matched_keys': 'dicts\drop_matched_keys.md'
    - docs: 
        - 'mkds_pyfile_parser': 'docs\mkds_pyfile_parser.md'
        - 'mkds_markdown_indexfile': 'docs\mkds_markdown_indexfile.md'
        - 'mkds_mod_mkdocs_yml_archi': 'docs\mkds_mod_mkdocs_yml_archi.md'
        - 'mkds_markdownfile_content': 'docs\mkds_markdownfile_content.md'
        - 'mkds_make_docfiles': 'docs\mkds_make_docfiles.md'
    - externs: 
        - 'empty_df': 'externs\empty_df.md'
    - fileio: 
        - 'Pickle': 'fileio\Pickle.md'
        - 'ConfigFile': 'fileio\ConfigFile.md'
        - 'paste_dir_content': 'fileio\paste_dir_content.md'
    - geometries: 
        - 'UPoint': 'geometries\UPoint.md'
        - 'ULine': 'geometries\ULine.md'
        - 'UPointCollection': 'geometries\UPointCollection.md'
        - 'ULineCollection': 'geometries\ULineCollection.md'
        - 'UGetAngle': 'geometries\UGetAngle.md'
        - 'removenans': 'geometries\removenans.md'
        - 'UChgtVar': 'geometries\UChgtVar.md'
        - 'orth_change': 'geometries\orth_change.md'
        - 'Corner_detection': 'geometries\Corner_detection.md'
        - 'Distance': 'geometries\Distance.md'
        - 'Distances': 'geometries\Distances.md'
        - 'Means': 'geometries\Means.md'
        - 'Trajectory_Window': 'geometries\Trajectory_Window.md'
    - iters: 
        - 'unique_pairs': 'iters\unique_pairs.md'
        - 'nest_iter': 'iters\nest_iter.md'
    - networks: 
        - 'StaticSQLEngine': 'networks\StaticSQLEngine.md'
        - 'open_sql': 'networks\open_sql.md'
        - 'is_port_open': 'networks\is_port_open.md'
    - pathes: 
        - 'list_recursive_files': 'pathes\list_recursive_files.md'
        - 'list_recursive_dirs': 'pathes\list_recursive_dirs.md'
        - 'list_toplevel_dirs': 'pathes\list_toplevel_dirs.md'
        - 'list_toplevel_files': 'pathes\list_toplevel_files.md'
        - 'separate_path_components': 'pathes\separate_path_components.md'
        - 'is_or_makedir': 'pathes\is_or_makedir.md'
        - 'remove_common_prefix': 'pathes\remove_common_prefix.md'
        - 'switch_root': 'pathes\switch_root.md'
        - 'get_most_recent_file': 'pathes\get_most_recent_file.md'
        - 'up_folder': 'pathes\up_folder.md'
        - 'folder_search': 'pathes\folder_search.md'
        - 're_folder_search': 'pathes\re_folder_search.md'
        - 'GetVersionnedPickles': 'pathes\GetVersionnedPickles.md'
        - 'BinarySearch': 'pathes\BinarySearch.md'
    - signals: 
        - 'splicedArrayBuilder': 'signals\splicedArrayBuilder.md'
        - 'splicedArray': 'signals\splicedArray.md'
        - 'removenans': 'signals\removenans.md'
        - 'get_array_splices_infos': 'signals\get_array_splices_infos.md'
    - strings: 
        - 'alphanum_sort': 'strings\alphanum_sort.md'
        - 'quick_regexp': 'strings\quick_regexp.md'
        - 'greek': 'strings\greek.md'
    - structs: 
        - 'sdict': 'structs\sdict.md'
        - 'sdict': 'structs\sdict.md'
        - 'TwoLayerDict': 'structs\TwoLayerDict.md'
        - 'func_io_typematch': 'structs\func_io_typematch.md'
        - 'get_properties_names': 'structs\get_properties_names.md'
    - workflows: 
        - 'CachedVariables': 'workflows\CachedVariables.md'
        - 'get_currentfile_git_repo_metadata': 'workflows\get_currentfile_git_repo_metadata.md'
        - 'ProgressBarImage': 'workflows\ProgressBarImage.md'
        - 'sizeof_fmt': 'workflows\sizeof_fmt.md'
        - 'singleton': 'workflows\singleton.md'
